spacemouse_to_servo:
  ros__parameters:
    input_topic: /spacenav/twist
    output_topic: /servo_node/delta_twist_cmds
    publish_hz: 50.0
    frame_id: ""
    input_timeout: 0.25
    enable_topic: /spacenav/joy
    require_enable_button: true
    enable_button_idx: 0
    linear_scale: 0.32
    linear_x_scale: 0.32
    linear_y_scale: 0.55
    linear_z_scale: 0.36
    angular_scale: 0.60
    deadband: 0.020
    clamp_abs: 0.75
    smoothing_alpha: 0.60
    max_linear_step: 0.050
    max_angular_step: 0.090
    sign_lx: 1.0
    sign_ly: -1.0
    sign_lz: -1.0
    sign_ax: 1.0
    sign_ay: -1.0
    sign_az: 1.0

spacemouse_gn01:
  ros__parameters:
    joy_topic: /spacenav/joy
    action_name: /flexiv_gripper_node/gripper_action
    open_button_idx: -1
    close_button_idx: -1
    toggle_button_idx: 1
    initial_toggle_is_open: false
    open_width: 0.09
    close_width: 0.01
    velocity: 0.10
    max_force: 20.0
    server_wait_timeout: 0.5
